version: '3.9'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - database:/var/lib/mysql/
    networks:
      - project

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress/
    networks:
      - project
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    hostname: localhost
    volumes:
      - wordpress:/var/www/wordpress/
    networks:
      - project
    depends_on:
      - wordpress
    ports:
      - "443:443"
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    hostname: localhost
    volumes:
      - wordpress:/ftp
    networks:
      - project
    ports:
      - "21:21"
      - "30000-30009:30000-30009"

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mbennani/data/database
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mbennani/data/wordpress

networks:
  project:
    driver: bridge