version: '3.9'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - database:/var/lib/mysql/
    networks:
      - project

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress/
    networks:
      - project
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    hostname: localhost
    volumes:
      - wordpress:/var/www/wordpress/
    networks:
      - project
    depends_on:
      - wordpress
    ports:
      - "443:443"
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    hostname: localhost
    volumes:
      - wordpress:/ftp
    networks:
      - project
    ports:
      - "21:21"
      - "30000-30009:30000-30009"

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    hostname: localhost
    volumes:
      - wordpress:/var/www/html
    networks:
      - project

  # adminer:
  #   container_name: adminer
  #   build: ./requirements/bonus/adminer
  #   hostname: localhost
  #   volumes:
  #     - adminer:/adminer
  #   networks:
  #     - project
  #   expose:
  #     - "9001"
  #   depends_on:
  #     - mariadb

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mbennani/data/database
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mbennani/data/wordpress
  # adminer:
  #   name: adminer
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device:  /home/mbennani/data/adminer
  #     o: bind

networks:
  project:
    driver: bridge