version: '3.9'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:oldest
    restart: always
    env_file: .env
    volumes:
      - database:/var/lib/mysql/
    networks:
      - project

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:oldest
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress/
    networks:
      - project
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:oldest
    volumes:
      - wordpress:/var/www/wordpress/
      - adminer:/adminer
    networks:
      - project
    depends_on:
      - wordpress
    ports:
      - "443:443"
      - "9090:9090"
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    image: ftp:oldest
    volumes:
      - wordpress:/ftp
    networks:
      - project
    ports:
      - "21:21"
      - "30000-30009:30000-30009"

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis:oldest
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - project

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer:oldest
    volumes:
      - adminer:/adminer
    networks:
      - project
    expose:
      - 8081
    depends_on:
      - wordpress

  website:
    container_name: website
    image: website:oldest
    build: ./requirements/bonus/website
    networks:
      - project
    ports:
      - "9191:9191"

volumes:
  database:
    name: database
    driver_opts:
      type: none
      o: bind
      device: /Users/mbennani/data/database
  wordpress:
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /Users/mbennani/data/wordpress
  adminer:
    name: adminer
    driver_opts:
      type: none
      device:  /Users/mbennani/data/adminer
      o: bind

networks:
  project: